=== grallewellyn/onearth/src/colormaps/schemas/ColorMap_v1.0.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="ColorMap">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="ColorMapEntry" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute type="xs:string" name="units" />
  </xs:complexType>
</xs:element>

<xs:element name="ColorMapEntry">
  <xs:complexType>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="rgb" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="\d{1,3},\d{1,3},\d{1,3}" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:boolean" name="transparent" default="false"/>
        <xs:attribute name="value">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[\[(]?((-?\d+(\.\d+)?(e[\+\-]\d+)?)|([\+\-]INF))(,((-?\d+(\.\d+)?(e[\+\-]\d+)?)|([\+\-]INF)))?[\])]?(,[\[(]?((-?\d+(\.\d+)?(e[\+\-]\d+)?)|([\+\-]INF))(,((-?\d+(\.\d+)?(e[\+\-]\d+)?)|([\+\-]INF)))?[\])]?)*" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="label" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:element>
</xs:schema>

=== grallewellyn/onearth/docker/sample_configs/colormaps/v1.0/MODIS_NDVI.xml
<?xml version="1.0" encoding="UTF-8"?>
<ColorMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="http://gibs.earthdata.nasa.gov/schemas/ColorMap_v1.0.xsd">
  <ColorMapEntry rgb="0,26,105" transparent="true" value="[-0.3,-0.2)" label="Fill" />
  <ColorMapEntry rgb="225,225,225" transparent="true" value="[-0.2000,-0.0999)" label="-0.200 - -0.100" />
  <ColorMapEntry rgb="225,225,226" transparent="true" value="[-0.0999,0.0001)" label="-0.100 - 0.000" />
  <ColorMapEntry rgb="241,236,236" transparent="false" value="[0.0001,0.0051)" label="0.000 - 0.005" />
  <ColorMapEntry rgb="241,236,237" transparent="false" value="[0.0051,0.0101)" label="0.005 - 0.010" />
  <ColorMapEntry rgb="239,231,231" transparent="false" value="[0.0101,0.0151)" label="0.010 - 0.015" />
  <ColorMapEntry rgb="239,231,232" transparent="false" value="[0.0151,0.0201)" label="0.015 - 0.020" />
  <ColorMapEntry rgb="236,226,226" transparent="false" value="[0.0201,0.0251)" label="0.020 - 0.025" />
  <ColorMapEntry rgb="236,226,227" transparent="false" value="[0.0251,0.0301)" label="0.025 - 0.030" />
  <ColorMapEntry rgb="226,216,216" transparent="false" value="[0.0301,0.0351)" label="0.030 - 0.035" />
  <ColorMapEntry rgb="226,216,217" transparent="false" value="[0.0351,0.0401)" label="0.035 - 0.040" />
  <ColorMapEntry rgb="225,217,212" transparent="false" value="[0.0401,0.0451)" label="0.040 - 0.045" />
  <ColorMapEntry rgb="225,217,213" transparent="false" value="[0.0451,0.0501)" label="0.045 - 0.050" />
  <ColorMapEntry rgb="224,218,210" transparent="false" value="[0.0501,0.0551)" label="0.050 - 0.055" />
  <ColorMapEntry rgb="224,218,211" transparent="false" value="[0.0551,0.0601)" label="0.055 - 0.060" />
  <ColorMapEntry rgb="221,213,203" transparent="false" value="[0.0601,0.0651)" label="0.060 - 0.065" />
  <ColorMapEntry rgb="221,213,204" transparent="false" value="[0.0651,0.0701)" label="0.065 - 0.070" />
  <ColorMapEntry rgb="229,219,205" transparent="false" value="[0.0701,0.0751)" label="0.070 - 0.075" />
  <ColorMapEntry rgb="229,219,206" transparent="false" value="[0.0751,0.0801)" label="0.075 - 0.080" />
  <ColorMapEntry rgb="225,210,197" transparent="false" value="[0.0801,0.0851)" label="0.080 - 0.085" />
  <ColorMapEntry rgb="225,210,198" transparent="false" value="[0.0851,0.0901)" label="0.085 - 0.090" />
  <ColorMapEntry rgb="223,206,193" transparent="false" value="[0.0901,0.0951)" label="0.090 - 0.095" />
  <ColorMapEntry rgb="223,206,194" transparent="false" value="[0.0951,0.1001)" label="0.095 - 0.100" />
  <ColorMapEntry rgb="221,201,188" transparent="false" value="[0.1001,0.1051)" label="0.100 - 0.105" />
  <ColorMapEntry rgb="221,201,189" transparent="false" value="[0.1051,0.1101)" label="0.105 - 0.110" />
  <ColorMapEntry rgb="215,196,179" transparent="false" value="[0.1101,0.1151)" label="0.110 - 0.115" />
  <ColorMapEntry rgb="215,196,180" transparent="false" value="[0.1151,0.1201)" label="0.115 - 0.120" />
  <ColorMapEntry rgb="209,192,171" transparent="false" value="[0.1201,0.1251)" label="0.120 - 0.125" />
  <ColorMapEntry rgb="209,192,172" transparent="false" value="[0.1251,0.1301)" label="0.125 - 0.130" />
  <ColorMapEntry rgb="205,186,158" transparent="false" value="[0.1301,0.1351)" label="0.130 - 0.135" />
  <ColorMapEntry rgb="205,186,159" transparent="false" value="[0.1351,0.1401)" label="0.135 - 0.140" />
  <ColorMapEntry rgb="200,181,165" transparent="false" value="[0.1401,0.1451)" label="0.140 - 0.145" />
  <ColorMapEntry rgb="200,181,166" transparent="false" value="[0.1451,0.1501)" label="0.145 - 0.150" />
  <ColorMapEntry rgb="192,176,150" transparent="false" value="[0.1501,0.1551)" label="0.150 - 0.155" />
  <ColorMapEntry rgb="192,176,151" transparent="false" value="[0.1551,0.1601)" label="0.155 - 0.160" />
  <ColorMapEntry rgb="185,171,155" transparent="false" value="[0.1601,0.1651)" label="0.160 - 0.165" />
  <ColorMapEntry rgb="185,171,156" transparent="false" value="[0.1651,0.1701)" label="0.165 - 0.170" />
  <ColorMapEntry rgb="180,165,149" transparent="false" value="[0.1701,0.1751)" label="0.170 - 0.175" />
  <ColorMapEntry rgb="180,165,150" transparent="false" value="[0.1751,0.1801)" label="0.175 - 0.180" />
  <ColorMapEntry rgb="176,159,142" transparent="false" value="[0.1801,0.1851)" label="0.180 - 0.185" />
  <ColorMapEntry rgb="176,159,143" transparent="false" value="[0.1851,0.1901)" label="0.185 - 0.190" />
  <ColorMapEntry rgb="176,155,137" transparent="false" value="[0.1901,0.1951)" label="0.190 - 0.195" />
  <ColorMapEntry rgb="176,155,138" transparent="false" value="[0.1951,0.2001)" label="0.195 - 0.200" />
  <ColorMapEntry rgb="177,152,131" transparent="false" value="[0.2001,0.2051)" label="0.200 - 0.205" />
  <ColorMapEntry rgb="177,152,132" transparent="false" value="[0.2051,0.2101)" label="0.205 - 0.210" />
  <ColorMapEntry rgb="176,149,125" transparent="false" value="[0.2101,0.2151)" label="0.210 - 0.215" />
  <ColorMapEntry rgb="176,149,126" transparent="false" value="[0.2151,0.2201)" label="0.215 - 0.220" />
  <ColorMapEntry rgb="176,146,120" transparent="false" value="[0.2201,0.2251)" label="0.220 - 0.225" />
  <ColorMapEntry rgb="176,146,121" transparent="false" value="[0.2251,0.2301)" label="0.225 - 0.230" />
  <ColorMapEntry rgb="172,141,115" transparent="false" value="[0.2301,0.2351)" label="0.230 - 0.235" />
  <ColorMapEntry rgb="172,141,116" transparent="false" value="[0.2351,0.2401)" label="0.235 - 0.240" />
  <ColorMapEntry rgb="169,137,110" transparent="false" value="[0.2401,0.2451)" label="0.240 - 0.245" />
  <ColorMapEntry rgb="169,137,111" transparent="false" value="[0.2451,0.2501)" label="0.245 - 0.250" />
  <ColorMapEntry rgb="165,132,104" transparent="false" value="[0.2501,0.2551)" label="0.250 - 0.255" />
  <ColorMapEntry rgb="165,132,105" transparent="false" value="[0.2551,0.2601)" label="0.255 - 0.260" />
  <ColorMapEntry rgb="161,128,99" transparent="false" value="[0.2601,0.2651)" label="0.260 - 0.265" />
  <ColorMapEntry rgb="161,128,100" transparent="false" value="[0.2651,0.2701)" label="0.265 - 0.270" />
  <ColorMapEntry rgb="157,124,94" transparent="false" value="[0.2701,0.2751)" label="0.270 - 0.275" />
  <ColorMapEntry rgb="157,124,95" transparent="false" value="[0.2751,0.2801)" label="0.275 - 0.280" />
  <ColorMapEntry rgb="154,110,89" transparent="false" value="[0.2801,0.2851)" label="0.280 - 0.285" />
  <ColorMapEntry rgb="154,110,90" transparent="false" value="[0.2851,0.2901)" label="0.285 - 0.290" />
  <ColorMapEntry rgb="150,90,70" transparent="false" value="[0.2901,0.2951)" label="0.290 - 0.295" />
  <ColorMapEntry rgb="150,90,71" transparent="false" value="[0.2951,0.3001)" label="0.295 - 0.300" />
  <ColorMapEntry rgb="191,222,119" transparent="false" value="[0.3001,0.3076)" label="0.3000 - 0.3075" />
  <ColorMapEntry rgb="191,222,120" transparent="false" value="[0.3076,0.3151)" label="0.3075 - 0.3150" />
  <ColorMapEntry rgb="176,207,104" transparent="false" value="[0.3151,0.3226)" label="0.3150 - 0.3225" />
  <ColorMapEntry rgb="176,207,105" transparent="false" value="[0.3226,0.3301)" label="0.3225 - 0.3300" />
  <ColorMapEntry rgb="167,204,75" transparent="false" value="[0.3301,0.3376)" label="0.3300 - 0.3375" />
  <ColorMapEntry rgb="167,204,76" transparent="false" value="[0.3376,0.3451)" label="0.3375 - 0.3450" />
  <ColorMapEntry rgb="164,198,61" transparent="false" value="[0.3451,0.3526)" label="0.3450 - 0.3525" />
  <ColorMapEntry rgb="164,198,62" transparent="false" value="[0.3526,0.3601)" label="0.3525 - 0.3600" />
  <ColorMapEntry rgb="160,192,48" transparent="false" value="[0.3601,0.3676)" label="0.3600 - 0.3675" />
  <ColorMapEntry rgb="160,192,49" transparent="false" value="[0.3676,0.3751)" label="0.3675 - 0.3750" />
  <ColorMapEntry rgb="150,186,32" transparent="false" value="[0.3751,0.3826)" label="0.3750 - 0.3825" />
  <ColorMapEntry rgb="150,186,33" transparent="false" value="[0.3826,0.3901)" label="0.3825 - 0.3900" />
  <ColorMapEntry rgb="143,183,21" transparent="false" value="[0.3901,0.3976)" label="0.3900 - 0.3975" />
  <ColorMapEntry rgb="143,183,22" transparent="false" value="[0.3976,0.4051)" label="0.3975 - 0.4050" />
  <ColorMapEntry rgb="135,179,10" transparent="false" value="[0.4051,0.4126)" label="0.4050 - 0.4125" />
  <ColorMapEntry rgb="135,179,11" transparent="false" value="[0.4126,0.4201)" label="0.4125 - 0.4200" />
  <ColorMapEntry rgb="128,176,5" transparent="false" value="[0.4201,0.4276)" label="0.4200 - 0.4275" />
  <ColorMapEntry rgb="128,176,6" transparent="false" value="[0.4276,0.4351)" label="0.4275 - 0.4350" />
  <ColorMapEntry rgb="120,173,0" transparent="false" value="[0.4351,0.4426)" label="0.4350 - 0.4425" />
  <ColorMapEntry rgb="120,173,1" transparent="false" value="[0.4426,0.4501)" label="0.4425 - 0.4500" />
  <ColorMapEntry rgb="110,170,0" transparent="false" value="[0.4501,0.4576)" label="0.4500 - 0.4575" />
  <ColorMapEntry rgb="110,170,1" transparent="false" value="[0.4576,0.4651)" label="0.4575 - 0.4650" />
  <ColorMapEntry rgb="100,166,0" transparent="false" value="[0.4651,0.4726)" label="0.4650 - 0.4725" />
  <ColorMapEntry rgb="100,166,1" transparent="false" value="[0.4726,0.4801)" label="0.4725 - 0.4800" />
  <ColorMapEntry rgb="93,163,0" transparent="false" value="[0.4801,0.4876)" label="0.4800 - 0.4875" />
  <ColorMapEntry rgb="93,163,1" transparent="false" value="[0.4876,0.4951)" label="0.4875 - 0.4950" />
  <ColorMapEntry rgb="86,161,0" transparent="false" value="[0.4951,0.5026)" label="0.4950 - 0.5025" />
  <ColorMapEntry rgb="86,161,1" transparent="false" value="[0.5026,0.5101)" label="0.5025 - 0.5100" />
  <ColorMapEntry rgb="82,152,0" transparent="false" value="[0.5101,0.5176)" label="0.5100 - 0.5175" />
  <ColorMapEntry rgb="82,152,1" transparent="false" value="[0.5176,0.5251)" label="0.5175 - 0.5250" />
  <ColorMapEntry rgb="83,151,0" transparent="false" value="[0.5251,0.5326)" label="0.5250 - 0.5325" />
