=== grallewellyn/onearth/src/colormaps/schemas/ColorMap_v1.3.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="ColorMaps">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="ColorMap" maxOccurs="unbounded" minOccurs="1" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="ColorMap">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="Entries" />
      <xs:element ref="Legend" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="title" use="required" />
    <xs:attribute type="xs:string" name="units" use="optional" />
  </xs:complexType>
</xs:element>


<xs:element name="Entries">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="ColorMapEntry" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="ColorMapEntry">
  <xs:complexType>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="rgb" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="\d{1,3},\d{1,3},\d{1,3}" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:boolean" name="transparent" default="false"/>
        <xs:attribute name="sourceValue">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[\[(]?((-?\d+(\.\d+)?(e[\+\-]\d+)?)|([\+\-]INF))(,((-?\d+(\.\d+)?(e[\+\-]\d+)?)|([\+\-]INF)))?[\])]?(,[\[(]?((-?\d+(\.\d+)?(e[\+\-]\d+)?)|([\+\-]INF))(,((-?\d+(\.\d+)?(e[\+\-]\d+)?)|([\+\-]INF)))?[\])]?)*" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="value">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[\[(]?((-?\d+(\.\d+)?(e[\+\-]\d+)?)|([\+\-]INF))(,((-?\d+(\.\d+)?(e[\+\-]\d+)?)|([\+\-]INF)))?[\])]?(,[\[(]?((-?\d+(\.\d+)?(e[\+\-]\d+)?)|([\+\-]INF))(,((-?\d+(\.\d+)?(e[\+\-]\d+)?)|([\+\-]INF)))?[\])]?)*" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:short" name="ref" use="required" />
        <xs:attribute type="xs:boolean" name="nodata" default="false" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:element>

<xs:element name="Legend">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="LegendEntry" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="continuous" />
          <xs:enumeration value="discrete" />
          <xs:enumeration value="classification" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute type="xs:string" name="minLabel" use="optional" />
    <xs:attribute type="xs:string" name="maxLabel" use="optional" />
  </xs:complexType>
</xs:element>

<xs:element name="LegendEntry">
  <xs:complexType>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="rgb" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="\d{1,3},\d{1,3},\d{1,3}" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="tooltip" use="required" />
        <xs:attribute type="xs:string" name="label" use="optional" />
        <xs:attribute type="xs:boolean" name="showTick" default="false" use="optional" />
        <xs:attribute type="xs:boolean" name="showLabel" default="false" use="optional" />
        <xs:attribute type="xs:short" name="id" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:element>
</xs:schema>

=== grallewellyn/onearth/src/test/colormap_html_sld_test_data/expected_outputs/test_SLDtoColorMap_v1_1_0_offset_factor_expected.xml
<?xml version="1.0" encoding="UTF-8"?>
<ColorMaps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="http://gibs.earthdata.nasa.gov/schemas/ColorMap_v1.3.xsd">
  <ColorMap title="No Data">
    <Entries>
      <ColorMapEntry rgb="0,0,0" transparent="true" label="No Data" nodata="true" ref="1" />
    </Entries>
    <Legend type="classification" >
      <LegendEntry rgb="0,0,0" id="1" />
    </Legend>
  </ColorMap>
  <ColorMap units="K">
    <Entries minLabel="&lt; 200.0 K"  maxLabel="&gt;= 340.0 K">
      <ColorMapEntry rgb="227,245,255" transparent="false" sourceValue="[-INF,126.66666666666667)" value="[-INF,200.0)" label="&lt; 200.0 K" ref="1" />
      <ColorMapEntry rgb="204,234,252" transparent="false" sourceValue="[126.66666666666667,127.06666666666666)" value="[200.0,200.6)" label="200.0 - 200.6 K" ref="2" />
      <ColorMapEntry rgb="203,232,251" transparent="false" sourceValue="[127.06666666666666,127.46666666666665)" value="[200.6,201.2)" label="200.6 - 201.2 K" ref="3" />
      <ColorMapEntry rgb="200,229,249" transparent="false" sourceValue="[127.46666666666665,127.86666666666667)" value="[201.2,201.8)" label="201.2 - 201.8 K" ref="4" />
      <ColorMapEntry rgb="198,227,247" transparent="false" sourceValue="[127.86666666666667,128.26666666666668)" value="[201.8,202.4)" label="201.8 - 202.4 K" ref="5" />
      <ColorMapEntry rgb="196,224,245" transparent="false" sourceValue="[128.26666666666668,128.66666666666666)" value="[202.4,203.0)" label="202.4 - 203.0 K" ref="6" />
      <ColorMapEntry rgb="194,221,243" transparent="false" sourceValue="[128.66666666666666,129.06666666666666)" value="[203.0,203.6)" label="203.0 - 203.6 K" ref="7" />
      <ColorMapEntry rgb="191,218,241" transparent="false" sourceValue="[129.06666666666666,129.46666666666667)" value="[203.6,204.2)" label="203.6 - 204.2 K" ref="8" />
      <ColorMapEntry rgb="189,215,239" transparent="false" sourceValue="[129.46666666666667,129.86666666666667)" value="[204.2,204.8)" label="204.2 - 204.8 K" ref="9" />
      <ColorMapEntry rgb="186,212,237" transparent="false" sourceValue="[129.86666666666667,130.26666666666668)" value="[204.8,205.4)" label="204.8 - 205.4 K" ref="10" />
      <ColorMapEntry rgb="183,209,234" transparent="false" sourceValue="[130.26666666666668,130.66666666666666)" value="[205.4,206.0)" label="205.4 - 206.0 K" ref="11" />
      <ColorMapEntry rgb="180,205,232" transparent="false" sourceValue="[130.66666666666666,131.06666666666666)" value="[206.0,206.6)" label="206.0 - 206.6 K" ref="12" />
      <ColorMapEntry rgb="177,201,229" transparent="false" sourceValue="[131.06666666666666,131.46666666666667)" value="[206.6,207.2)" label="206.6 - 207.2 K" ref="13" />
      <ColorMapEntry rgb="174,198,227" transparent="false" sourceValue="[131.46666666666667,131.86666666666667)" value="[207.2,207.8)" label="207.2 - 207.8 K" ref="14" />
      <ColorMapEntry rgb="171,194,224" transparent="false" sourceValue="[131.86666666666667,132.26666666666668)" value="[207.8,208.4)" label="207.8 - 208.4 K" ref="15" />
      <ColorMapEntry rgb="168,190,221" transparent="false" sourceValue="[132.26666666666668,132.66666666666666)" value="[208.4,209.0)" label="208.4 - 209.0 K" ref="16" />
      <ColorMapEntry rgb="165,187,219" transparent="false" sourceValue="[132.66666666666666,133.06666666666666)" value="[209.0,209.6)" label="209.0 - 209.6 K" ref="17" />
      <ColorMapEntry rgb="162,183,216" transparent="false" sourceValue="[133.06666666666666,133.46666666666667)" value="[209.6,210.2)" label="209.6 - 210.2 K" ref="18" />
      <ColorMapEntry rgb="159,179,213" transparent="false" sourceValue="[133.46666666666667,133.86666666666667)" value="[210.2,210.8)" label="210.2 - 210.8 K" ref="19" />
      <ColorMapEntry rgb="156,175,211" transparent="false" sourceValue="[133.86666666666667,134.26666666666668)" value="[210.8,211.4)" label="210.8 - 211.4 K" ref="20" />
      <ColorMapEntry rgb="154,172,208" transparent="false" sourceValue="[134.26666666666668,134.66666666666666)" value="[211.4,212.0)" label="211.4 - 212.0 K" ref="21" />
      <ColorMapEntry rgb="151,168,206" transparent="false" sourceValue="[134.66666666666666,135.06666666666666)" value="[212.0,212.6)" label="212.0 - 212.6 K" ref="22" />
      <ColorMapEntry rgb="149,165,203" transparent="false" sourceValue="[135.06666666666666,135.46666666666667)" value="[212.6,213.2)" label="212.6 - 213.2 K" ref="23" />
      <ColorMapEntry rgb="147,161,201" transparent="false" sourceValue="[135.46666666666667,135.86666666666667)" value="[213.2,213.8)" label="213.2 - 213.8 K" ref="24" />
      <ColorMapEntry rgb="144,158,199" transparent="false" sourceValue="[135.86666666666667,136.26666666666668)" value="[213.8,214.4)" label="213.8 - 214.4 K" ref="25" />
      <ColorMapEntry rgb="142,154,197" transparent="false" sourceValue="[136.26666666666668,136.66666666666666)" value="[214.4,215.0)" label="214.4 - 215.0 K" ref="26" />
      <ColorMapEntry rgb="141,150,194" transparent="false" sourceValue="[136.66666666666666,137.06666666666666)" value="[215.0,215.6)" label="215.0 - 215.6 K" ref="27" />
      <ColorMapEntry rgb="140,146,192" transparent="false" sourceValue="[137.06666666666666,137.46666666666667)" value="[215.6,216.2)" label="215.6 - 216.2 K" ref="28" />
      <ColorMapEntry rgb="139,142,190" transparent="false" sourceValue="[137.46666666666667,137.86666666666667)" value="[216.2,216.8)" label="216.2 - 216.8 K" ref="29" />
      <ColorMapEntry rgb="138,138,188" transparent="false" sourceValue="[137.86666666666667,138.26666666666668)" value="[216.8,217.4)" label="216.8 - 217.4 K" ref="30" />
      <ColorMapEntry rgb="138,133,186" transparent="false" sourceValue="[138.26666666666668,138.66666666666666)" value="[217.4,218.0)" label="217.4 - 218.0 K" ref="31" />
      <ColorMapEntry rgb="139,129,184" transparent="false" sourceValue="[138.66666666666666,139.06666666666666)" value="[218.0,218.6)" label="218.0 - 218.6 K" ref="32" />
      <ColorMapEntry rgb="139,125,182" transparent="false" sourceValue="[139.06666666666666,139.46666666666667)" value="[218.6,219.2)" label="218.6 - 219.2 K" ref="33" />
      <ColorMapEntry rgb="140,121,180" transparent="false" sourceValue="[139.46666666666667,139.86666666666667)" value="[219.2,219.8)" label="219.2 - 219.8 K" ref="34" />
      <ColorMapEntry rgb="140,117,178" transparent="false" sourceValue="[139.86666666666667,140.26666666666668)" value="[219.8,220.4)" label="219.8 - 220.4 K" ref="35" />
      <ColorMapEntry rgb="140,114,176" transparent="false" sourceValue="[140.26666666666668,140.66666666666666)" value="[220.4,221.0)" label="220.4 - 221.0 K" ref="36" />
      <ColorMapEntry rgb="140,110,174" transparent="false" sourceValue="[140.66666666666666,141.06666666666666)" value="[221.0,221.6)" label="221.0 - 221.6 K" ref="37" />
      <ColorMapEntry rgb="139,106,172" transparent="false" sourceValue="[141.06666666666666,141.46666666666667)" value="[221.6,222.2)" label="221.6 - 222.2 K" ref="38" />
      <ColorMapEntry rgb="138,102,170" transparent="false" sourceValue="[141.46666666666667,141.86666666666667)" value="[222.2,222.8)" label="222.2 - 222.8 K" ref="39" />
      <ColorMapEntry rgb="137,99,167" transparent="false" sourceValue="[141.86666666666667,142.26666666666668)" value="[222.8,223.4)" label="222.8 - 223.4 K" ref="40" />
      <ColorMapEntry rgb="135,95,165" transparent="false" sourceValue="[142.26666666666668,142.66666666666666)" value="[223.4,224.0)" label="223.4 - 224.0 K" ref="41" />
      <ColorMapEntry rgb="133,92,162" transparent="false" sourceValue="[142.66666666666666,143.06666666666666)" value="[224.0,224.6)" label="224.0 - 224.6 K" ref="42" />
      <ColorMapEntry rgb="130,89,159" transparent="false" sourceValue="[143.06666666666666,143.46666666666667)" value="[224.6,225.2)" label="224.6 - 225.2 K" ref="43" />
      <ColorMapEntry rgb="126,86,157" transparent="false" sourceValue="[143.46666666666667,143.86666666666667)" value="[225.2,225.8)" label="225.2 - 225.8 K" ref="44" />
      <ColorMapEntry rgb="122,83,154" transparent="false" sourceValue="[143.86666666666667,144.26666666666668)" value="[225.8,226.4)" label="225.8 - 226.4 K" ref="45" />
      <ColorMapEntry rgb="117,80,151" transparent="false" sourceValue="[144.26666666666668,144.66666666666666)" value="[226.4,227.0)" label="226.4 - 227.0 K" ref="46" />
      <ColorMapEntry rgb="113,77,148" transparent="false" sourceValue="[144.66666666666666,145.06666666666666)" value="[227.0,227.6)" label="227.0 - 227.6 K" ref="47" />
      <ColorMapEntry rgb="107,74,145" transparent="false" sourceValue="[145.06666666666666,145.46666666666667)" value="[227.6,228.2)" label="227.6 - 228.2 K" ref="48" />
      <ColorMapEntry rgb="102,71,141" transparent="false" sourceValue="[145.46666666666667,145.86666666666667)" value="[228.2,228.8)" label="228.2 - 228.8 K" ref="49" />
      <ColorMapEntry rgb="96,68,138" transparent="false" sourceValue="[145.86666666666667,146.26666666666668)" value="[228.8,229.4)" label="228.8 - 229.4 K" ref="50" />
      <ColorMapEntry rgb="90,65,134" transparent="false" sourceValue="[146.26666666666668,146.66666666666666)" value="[229.4,230.0)" label="229.4 - 230.0 K" ref="51" />
      <ColorMapEntry rgb="83,63,130" transparent="false" sourceValue="[146.66666666666666,147.06666666666666)" value="[230.0,230.6)" label="230.0 - 230.6 K" ref="52" />
      <ColorMapEntry rgb="77,60,127" transparent="false" sourceValue="[147.06666666666666,147.46666666666667)" value="[230.6,231.2)" label="230.6 - 231.2 K" ref="53" />
      <ColorMapEntry rgb="70,57,123" transparent="false" sourceValue="[147.46666666666667,147.86666666666667)" value="[231.2,231.8)" label="231.2 - 231.8 K" ref="54" />
      <ColorMapEntry rgb="64,54,119" transparent="false" sourceValue="[147.86666666666667,148.26666666666668)" value="[231.8,232.4)" label="231.8 - 232.4 K" ref="55" />
